import { useState, useEffect, useCallback, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  ChevronRight,
  ChevronDown,
  FileText,
  FolderOpen,
  Home,
  Save,
  Globe,
  Cpu,
  Terminal,
  Copy,
  Check,
  Sparkles,
  Loader,
  AlertTriangle,
  Zap,
  Clock,
  BarChart2,
} from 'lucide-react'
import { api } from '../api'
import MarkdownPreview from '../components/MarkdownPreview'

// ── Helpers ──────────────────────────────────────────────

function buildFileTree(skills) {
  const root = {}
  for (const skill of skills) {
    const path = skill.tags?.[0] || skill.name
    const parts = path.split('/')
    let node = root
    for (let i = 0; i < parts.length - 1; i++) {
      if (!node[parts[i]]) node[parts[i]] = { __children: {} }
      if (!node[parts[i]].__children) node[parts[i]].__children = {}
      node = node[parts[i]].__children
    }
    const filename = parts[parts.length - 1]
    node[filename] = { __skill: skill }
  }
  return root
}

function getBreadcrumbs(skill, projectName) {
  if (!skill) return [projectName]
  const path = skill.tags?.[0] || skill.name
  return [projectName, ...path.split('/')]
}

function CopyButton({ text }) {
  const [copied, setCopied] = useState(false)
  const handleCopy = async () => {
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }
  return (
    <button
      onClick={handleCopy}
      style={{ padding: 4, background: 'transparent', border: 0, cursor: 'pointer', color: copied ? '#000' : '#aaa', display: 'flex' }}
      title="Copy"
    >
      {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
    </button>
  )
}

// Format analysis result as a markdown document
function formatAnalysisMarkdown(analysis, projectName, skills) {
  const lines = []
  lines.push(`# doso analysis: ${projectName}`)
  lines.push('')
  lines.push(`*Auto-generated by doso.dev on ${new Date().toLocaleDateString()}*`)
  lines.push('')

  if (analysis.project_summary) {
    lines.push('## Project Overview')
    lines.push('')
    lines.push(analysis.project_summary)
    lines.push('')
  }

  if (analysis.skill_summaries?.length > 0) {
    lines.push('## Skills')
    lines.push('')
    for (const s of analysis.skill_summaries) {
      lines.push(`### ${s.name}`)
      lines.push(s.purpose || '')
      if (s.strengths?.length > 0) {
        lines.push(`- **Strengths:** ${s.strengths.join(', ')}`)
      }
      if (s.weaknesses?.length > 0) {
        lines.push(`- **Weaknesses:** ${s.weaknesses.join(', ')}`)
      }
      lines.push('')
    }
  }

  const score = analysis.health_score
  if (score) {
    lines.push('## Health Score')
    lines.push('')
    lines.push(`**Overall: ${score.overall}/100**`)
    if (score.breakdown) {
      lines.push(`- Clarity: ${score.breakdown.clarity}/100`)
      lines.push(`- Consistency: ${score.breakdown.consistency}/100`)
      lines.push(`- Coverage: ${score.breakdown.coverage}/100`)
      lines.push(`- Efficiency: ${score.breakdown.efficiency}/100`)
    }
    if (score.summary) lines.push(`\n${score.summary}`)
    lines.push('')
  }

  if (analysis.suggestions?.length > 0) {
    lines.push('## Improvement Suggestions')
    lines.push('')
    for (const s of analysis.suggestions) {
      const priority = s.priority === 'high' ? '!!!' : s.priority === 'medium' ? '!!' : '!'
      lines.push(`### ${priority} ${s.title}`)
      if (s.skill_name) lines.push(`*Applies to: ${s.skill_name}*`)
      lines.push('')
      lines.push(s.description)
      lines.push('')
    }
  }

  if (analysis.coverage_gaps?.length > 0) {
    lines.push('## Coverage Gaps')
    lines.push('')
    for (const g of analysis.coverage_gaps) {
      lines.push(`- **${g.gap}**: ${g.suggestion}`)
    }
    lines.push('')
  }

  if (analysis.cross_skill_contradictions?.length > 0) {
    lines.push('## Contradictions')
    lines.push('')
    for (const c of analysis.cross_skill_contradictions) {
      lines.push(`- **${c.skill_a} vs ${c.skill_b}** (${c.severity}): ${c.description}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

// ── File Tree Component ──────────────────────────────────

function TreeNode({ name, node, depth = 0, selectedId, onSelect }) {
  const [open, setOpen] = useState(true)

  if (node.__skill) {
    const skill = node.__skill
    const isSelected = selectedId === skill.id
    const isDoso = name === 'doso_readme' || name === 'doso_readme.md'
    return (
      <button
        onClick={() => onSelect(skill)}
        className="w-full text-left flex items-center gap-1.5"
        style={{
          padding: '5px 8px',
          paddingLeft: 8 + depth * 16,
          fontSize: 12,
          color: isSelected ? '#000' : isDoso ? '#D4A843' : '#555',
          fontWeight: isSelected ? 600 : 400,
          fontStyle: isDoso ? 'italic' : 'normal',
          background: isSelected ? '#f0f0f0' : 'transparent',
          border: 0,
          borderRadius: 3,
          cursor: 'pointer',
          transition: 'background 80ms',
        }}
        onMouseEnter={(e) => { if (!isSelected) e.currentTarget.style.background = '#f5f5f5' }}
        onMouseLeave={(e) => { if (!isSelected) e.currentTarget.style.background = 'transparent' }}
      >
        {isDoso ? (
          <Sparkles className="w-3.5 h-3.5 shrink-0" style={{ color: '#D4A843' }} />
        ) : (
          <FileText className="w-3.5 h-3.5 shrink-0" style={{ color: '#D4A843' }} />
        )}
        <span className="truncate">{name}</span>
      </button>
    )
  }

  // Directory node
  const children = node.__children || node
  const entries = Object.entries(children).filter(([k]) => k !== '__children')
  if (entries.length === 0) return null

  return (
    <div>
      <button
        onClick={() => setOpen(!open)}
        className="w-full text-left flex items-center gap-1.5"
        style={{
          padding: '5px 8px',
          paddingLeft: 8 + depth * 16,
          fontSize: 12,
          color: '#666',
          fontWeight: 500,
          background: 'transparent',
          border: 0,
          cursor: 'pointer',
        }}
      >
        {open ? <ChevronDown className="w-3 h-3 shrink-0" /> : <ChevronRight className="w-3 h-3 shrink-0" />}
        <FolderOpen className="w-3.5 h-3.5 shrink-0" style={{ color: '#888' }} />
        <span className="truncate">{name}</span>
      </button>
      {open && entries.map(([key, child]) => (
        <TreeNode
          key={key}
          name={key}
          node={child}
          depth={depth + 1}
          selectedId={selectedId}
          onSelect={onSelect}
        />
      ))}
    </div>
  )
}

// ── Floating Toolbar ──────────────────────────────────────

function FloatingToolbar({ skill }) {
  const [openPanel, setOpenPanel] = useState(null)

  if (!skill?.id) return null

  const base = window.location.origin
  const panels = [
    { key: 'api', icon: Globe, label: 'REST API', url: `${base}/api/v1/skills/${skill.id}`, desc: 'Full skill object as JSON' },
    { key: 'mcp', icon: Cpu, label: 'MCP Resource', url: `${base}/api/v1/mcp/skills/${skill.id}`, desc: 'MCP-compatible resource format' },
    { key: 'raw', icon: Terminal, label: 'Raw Markdown', url: `${base}/api/v1/skills/${skill.id}/raw`, desc: 'Plain text — paste in your agent' },
  ]

  return (
    <>
      {panels.map((p) => (
        <button
          key={p.key}
          onClick={() => setOpenPanel(openPanel === p.key ? null : p.key)}
          title={p.label}
          style={{
            width: 32, height: 32, display: 'flex', alignItems: 'center', justifyContent: 'center',
            border: 0, borderRadius: 6, background: openPanel === p.key ? '#f0f0f0' : 'transparent',
            cursor: 'pointer', color: openPanel === p.key ? '#000' : '#888', transition: 'all 80ms',
          }}
          onMouseEnter={(e) => { e.currentTarget.style.background = '#f0f0f0' }}
          onMouseLeave={(e) => { if (openPanel !== p.key) e.currentTarget.style.background = 'transparent' }}
        >
          <p.icon className="w-4 h-4" />
        </button>
      ))}
      {/* Popover panel */}
      {openPanel && (() => {
        const p = panels.find((x) => x.key === openPanel)
        if (!p) return null
        return (
          <div className="animate-fade-in" style={{
            position: 'absolute', right: 44, top: 0, width: 300,
            background: '#fff', border: '1px solid #e5e5e5', borderRadius: 8, padding: 14,
            boxShadow: '0 4px 16px rgba(0,0,0,0.1)',
          }}>
            <div className="flex items-center justify-between" style={{ marginBottom: 8 }}>
              <span style={{ fontSize: 12, fontWeight: 600, color: '#000' }}>{p.label}</span>
              <CopyButton text={p.url} />
            </div>
            <div style={{
              padding: '8px 10px', background: '#f5f5f5', borderRadius: 4,
              fontFamily: 'JetBrains Mono, monospace', fontSize: 11, color: '#333',
              wordBreak: 'break-all', lineHeight: 1.5,
            }}>
              <span style={{ background: '#000', color: '#fff', padding: '1px 5px', borderRadius: 2, fontSize: 10, fontWeight: 700, marginRight: 6 }}>GET</span>
              {p.url}
            </div>
            <p style={{ fontSize: 11, color: '#888', marginTop: 8 }}>{p.desc}</p>
          </div>
        )
      })()}
    </>
  )
}

// ── Analysis Pill (in breadcrumb bar) ─────────────────────

function AnalysisPill({ status, result, onToggle, expanded }) {
  if (status === 'idle') return null

  return (
    <button
      onClick={status === 'done' || status === 'error' ? onToggle : undefined}
      className="flex items-center gap-2"
      style={{
        padding: '4px 12px',
        borderRadius: 100,
        background: status === 'running' ? '#f5f3ee' : status === 'done' ? '#f0f0f0' : '#f5f5f5',
        border: '1px solid',
        borderColor: status === 'running' ? '#e8e0d0' : '#e5e5e5',
        cursor: status === 'done' || status === 'error' ? 'pointer' : 'default',
        fontSize: 11,
        color: status === 'running' ? '#8a7340' : '#555',
        fontWeight: 500,
        whiteSpace: 'nowrap',
        transition: 'all 150ms',
        position: 'relative',
        overflow: 'hidden',
      }}
    >
      {/* Progress bar background for running state */}
      {status === 'running' && (
        <div style={{
          position: 'absolute',
          left: 0,
          top: 0,
          bottom: 0,
          background: 'linear-gradient(90deg, #ece4d4 0%, #f5f0e5 50%, #ece4d4 100%)',
          backgroundSize: '200% 100%',
          animation: 'shimmer 1.5s ease-in-out infinite',
          width: '100%',
          borderRadius: 100,
        }} />
      )}

      <span style={{ position: 'relative', display: 'flex', alignItems: 'center', gap: 6 }}>
        {status === 'running' && (
          <>
            <Loader className="w-3 h-3" style={{ animation: 'spin 1s linear infinite' }} />
            Analyzing skills...
          </>
        )}
        {status === 'done' && (
          <>
            <Sparkles className="w-3 h-3" style={{ color: '#D4A843' }} />
            {result?.suggestions?.length > 0
              ? `${result.suggestions.length} suggestion${result.suggestions.length !== 1 ? 's' : ''}`
              : 'Analysis complete'}
            {result?.health_score?.overall != null && (
              <span style={{ color: '#aaa', fontWeight: 400 }}>
                &middot; {result.health_score.overall}/100
              </span>
            )}
          </>
        )}
        {status === 'error' && (
          <>
            <AlertTriangle className="w-3 h-3" style={{ color: '#aaa' }} />
            Analysis unavailable
          </>
        )}
      </span>
    </button>
  )
}

// ── Analysis Dropdown Panel ───────────────────────────────

function AnalysisDropdown({ result, onClose, scheduleConfig, onToggleSchedule, onSetFrequency, onRunNow, pendingCount }) {
  if (!result) return null

  const analysis = result

  return (
    <div
      className="animate-fade-in"
      style={{
        position: 'absolute',
        top: 44,
        left: 0,
        right: 0,
        zIndex: 20,
        background: '#fff',
        borderBottom: '1px solid #e5e5e5',
        boxShadow: '0 4px 16px rgba(0,0,0,0.08)',
        maxHeight: '60vh',
        overflowY: 'auto',
        padding: '16px 20px',
      }}
    >
      <div className="flex items-center justify-between" style={{ marginBottom: 16 }}>
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4" style={{ color: '#D4A843' }} />
          <span style={{ fontSize: 14, fontWeight: 600, color: '#000' }}>Skill Analysis</span>
          {analysis.health_score?.overall != null && (
            <span className="badge-gray" style={{ fontSize: 10 }}>
              Health: {analysis.health_score.overall}/100
            </span>
          )}
        </div>
        <button
          onClick={onClose}
          style={{ fontSize: 11, color: '#888', background: 'none', border: 0, cursor: 'pointer', padding: '4px 8px' }}
        >
          Close
        </button>
      </div>

      {/* Project summary */}
      {analysis.project_summary && (
        <div style={{ padding: '10px 14px', background: '#fafafa', borderRadius: 6, marginBottom: 16, fontSize: 13, color: '#333', lineHeight: 1.6 }}>
          {analysis.project_summary}
        </div>
      )}

      {/* Suggestions */}
      {analysis.suggestions?.length > 0 && (
        <div style={{ marginBottom: 16 }}>
          <h4 style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
            Improvement Suggestions
          </h4>
          <div className="space-y-2">
            {analysis.suggestions.map((s, i) => (
              <div key={i} style={{ padding: '10px 14px', background: '#f5f5f5', borderRadius: 6, borderLeft: `3px solid ${s.priority === 'high' ? '#D4A843' : s.priority === 'medium' ? '#ddd' : '#eee'}` }}>
                <div className="flex items-center gap-2" style={{ marginBottom: 4 }}>
                  <Zap className="w-3 h-3 shrink-0" style={{ color: '#D4A843' }} />
                  <span style={{ fontSize: 12, fontWeight: 600, color: '#000' }}>{s.title}</span>
                  {s.skill_name && <span className="badge-gray" style={{ fontSize: 9 }}>{s.skill_name}</span>}
                  {s.category && <span className="badge-ochre" style={{ fontSize: 9 }}>{s.category}</span>}
                </div>
                <p style={{ fontSize: 12, color: '#555', lineHeight: 1.5, paddingLeft: 18 }}>{s.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Coverage gaps */}
      {analysis.coverage_gaps?.length > 0 && (
        <div style={{ marginBottom: 16 }}>
          <h4 style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
            Coverage Gaps
          </h4>
          {analysis.coverage_gaps.map((g, i) => (
            <div key={i} className="flex items-start gap-2" style={{ marginBottom: 6 }}>
              <AlertTriangle className="w-3 h-3 shrink-0" style={{ color: '#D4A843', marginTop: 2 }} />
              <span style={{ fontSize: 12, color: '#333', lineHeight: 1.5 }}>
                <strong>{g.gap}:</strong> {g.suggestion}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* Contradictions */}
      {analysis.cross_skill_contradictions?.length > 0 && (
        <div>
          <h4 style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
            Contradictions
          </h4>
          {analysis.cross_skill_contradictions.map((c, i) => (
            <div key={i} className="flex items-start gap-2" style={{ marginBottom: 6 }}>
              <AlertTriangle className="w-3 h-3 shrink-0" style={{ color: '#c44', marginTop: 2 }} />
              <span style={{ fontSize: 12, color: '#333', lineHeight: 1.5 }}>
                <strong>{c.skill_a} vs {c.skill_b}</strong> ({c.severity}): {c.description}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* Health breakdown */}
      {analysis.health_score?.breakdown && (
        <div style={{ marginTop: 16, paddingTop: 12, borderTop: '1px solid #f0f0f0' }}>
          <h4 style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
            Health Breakdown
          </h4>
          <div className="grid grid-cols-4 gap-3">
            {Object.entries(analysis.health_score.breakdown).map(([key, val]) => (
              <div key={key} style={{ textAlign: 'center' }}>
                <div style={{ fontSize: 18, fontWeight: 700, color: '#000' }}>{val}</div>
                <div style={{ fontSize: 10, color: '#888', textTransform: 'capitalize' }}>{key}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Scheduled auto-optimization */}
      <div style={{ marginTop: 16, paddingTop: 12, borderTop: '1px solid #f0f0f0' }}>
        <h4 style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 10 }}>
          Auto-Optimize
        </h4>
        <div className="flex items-center justify-between" style={{ marginBottom: 8 }}>
          <span style={{ fontSize: 12, color: '#333' }}>Enable scheduled optimization</span>
          <input
            type="checkbox"
            className="toggle-switch"
            checked={scheduleConfig?.enabled || false}
            onChange={(e) => onToggleSchedule(e.target.checked)}
          />
        </div>
        <div className="flex items-center gap-2" style={{ marginBottom: 8 }}>
          <span style={{ fontSize: 11, color: '#888' }}>Frequency:</span>
          {['daily', 'weekly'].map((f) => (
            <button
              key={f}
              onClick={() => onSetFrequency(f)}
              style={{
                padding: '3px 10px', fontSize: 10, borderRadius: 2, cursor: 'pointer',
                border: '1px solid #e5e5e5',
                background: scheduleConfig?.frequency === f ? '#000' : '#fff',
                color: scheduleConfig?.frequency === f ? '#fff' : '#666',
              }}
            >{f}</button>
          ))}
        </div>
        {scheduleConfig?.last_run && (
          <div style={{ fontSize: 10, color: '#aaa', marginBottom: 8 }}>
            Last run: {new Date(scheduleConfig.last_run).toLocaleDateString()}
          </div>
        )}
        <div className="flex items-center gap-3">
          <button onClick={onRunNow} className="btn-secondary btn-sm" style={{ fontSize: 10 }}>Run now</button>
          {pendingCount > 0 && (
            <span className="badge-ochre" style={{ fontSize: 10 }}>{pendingCount} pending</span>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Inline SVG Icons ─────────────────────────────────────

function PencilIcon({ color = 'currentColor' }) {
  return (
    <svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke={color} strokeWidth="1.5">
      <path d="M11.5 1.5l3 3L5 14H2v-3L11.5 1.5z" />
    </svg>
  )
}

function EyeIcon({ color = 'currentColor' }) {
  return (
    <svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke={color} strokeWidth="1.5">
      <path d="M1 8s3-5 7-5 7 5 7 5-3 5-7 5-7-5-7-5z" />
      <circle cx="8" cy="8" r="2" />
    </svg>
  )
}

function BeakerIcon({ color = 'currentColor' }) {
  return (
    <svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke={color} strokeWidth="1.5">
      <path d="M6 1v5l-4 6.5c-.3.5.1 1 .6 1h10.8c.5 0 .9-.5.6-1L10 6V1" />
      <path d="M4.5 1h7" />
    </svg>
  )
}

// ── Prompt Linting ───────────────────────────────────────

const VAGUE_PHRASES = ['be helpful', 'do your best', 'try to', 'if possible', 'as needed', 'when appropriate']

function lintContent(text) {
  if (!text) return []
  const warnings = []
  const lower = text.toLowerCase()

  // Excessive length
  if (text.length > 8000) {
    warnings.push({ type: 'length', msg: `Content is ${Math.round(text.length / 1000)}k chars — consider trimming` })
  }

  // Vague phrases
  for (const phrase of VAGUE_PHRASES) {
    if (lower.includes(phrase)) {
      warnings.push({ type: 'vague', msg: `Vague phrase: "${phrase}"` })
      break // only show one
    }
  }

  // Contradictions: "always" + "never" in similar context
  if (lower.includes('always') && lower.includes('never')) {
    warnings.push({ type: 'contradiction', msg: 'Contains both "always" and "never" — check for contradictions' })
  }

  // Missing structure
  if (text.length > 500 && !text.includes('#')) {
    warnings.push({ type: 'structure', msg: 'No headers found — consider adding structure with #' })
  }

  return warnings.slice(0, 3)
}

// ── Simple Diff Helper ───────────────────────────────────

function simpleDiff(oldText, newText) {
  const oldLines = (oldText || '').split('\n')
  const newLines = (newText || '').split('\n')
  const oldSet = new Set(oldLines)
  const newSet = new Set(newLines)
  const result = []
  for (const line of oldLines) {
    if (!newSet.has(line)) result.push({ type: 'remove', text: line })
  }
  for (const line of newLines) {
    if (!oldSet.has(line)) result.push({ type: 'add', text: line })
  }
  return result
}

// ── Main ProjectView ──────────────────────────────────────

export default function ProjectView() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [project, setProject] = useState(null)
  const [skills, setSkills] = useState([])
  const [selectedSkill, setSelectedSkill] = useState(null)
  const [content, setContent] = useState('')
  const [dirty, setDirty] = useState(false)
  const [saving, setSaving] = useState(false)
  const [loading, setLoading] = useState(true)
  const [viewMode, setViewMode] = useState('edit') // edit | preview | test

  // Analysis state
  const [analysisStatus, setAnalysisStatus] = useState('idle')
  const [analysisResult, setAnalysisResult] = useState(null)
  const [analysisExpanded, setAnalysisExpanded] = useState(false)
  const analysisRanRef = useRef(false)

  // Optimize state
  const [optimizeStatus, setOptimizeStatus] = useState('idle') // idle | running | done
  const [optimizeResult, setOptimizeResult] = useState(null)
  const [optimizeOpen, setOptimizeOpen] = useState(false)

  // Version history state
  const [versions, setVersions] = useState([])
  const [versionsOpen, setVersionsOpen] = useState(false)
  const [selectedVersion, setSelectedVersion] = useState(null)

  // Playground state
  const [testMessage, setTestMessage] = useState('')
  const [testResponse, setTestResponse] = useState(null)
  const [testRunning, setTestRunning] = useState(false)

  // Analytics state
  const [analyticsData, setAnalyticsData] = useState(null)
  const [analyticsOpen, setAnalyticsOpen] = useState(false)

  // Scheduler state
  const [scheduleConfig, setScheduleConfig] = useState(null)
  const [pendingOpts, setPendingOpts] = useState([])

  // Linting state
  const [lintWarnings, setLintWarnings] = useState([])
  const lintTimerRef = useRef(null)

  useEffect(() => {
    loadProject()
  }, [id])

  async function loadProject() {
    try {
      const res = await api.getProject(id)
      const data = res.data
      setProject(data)
      setSkills(data.skills || [])

      // Select first skill by default
      if (data.skills?.length > 0) {
        selectSkillDirect(data.skills[0])
      }
    } catch (err) {
      console.error('Failed to load project:', err)
      navigate('/')
    } finally {
      setLoading(false)
    }
  }

  // Auto-start analysis once project loads
  useEffect(() => {
    if (skills.length === 0 || analysisRanRef.current) return
    analysisRanRef.current = true
    runAnalysis(skills)
  }, [skills])

  async function runAnalysis(skillList) {
    setAnalysisStatus('running')
    try {
      const payload = {
        skills: skillList.map((s) => ({ id: s.id, name: s.name, content: s.content })),
      }
      const res = await api.analyzeProject(payload)
      const data = res.data
      const analysis = data.analysis || data

      setAnalysisResult(analysis)
      setAnalysisStatus('done')

      // Create doso_readme document from analysis
      createDosoReadme(analysis, skillList)
    } catch {
      setAnalysisStatus('error')
    }
  }

  async function createDosoReadme(analysis, skillList) {
    try {
      const markdownContent = formatAnalysisMarkdown(analysis, project?.name || 'Project', skillList)
      const res = await api.createSkill({
        name: 'doso_readme',
        description: 'Auto-generated project analysis by doso.dev',
        content: markdownContent,
        category: 'General',
        tags: ['doso_readme', 'analysis'],
        is_public: false,
        project_id: id,
      })

      // Add to the project's skill list
      const newSkill = res.data
      if (newSkill?.id) {
        // Link it to the project
        try {
          await api.addSkillToProject(id, newSkill.id)
        } catch {
          // ignore if linking fails
        }
        setSkills((prev) => [...prev, newSkill])
      }
    } catch (err) {
      console.error('Failed to create doso_readme:', err)
    }
  }

  function selectSkillDirect(skill) {
    setSelectedSkill(skill)
    setContent(skill.content || '')
    setDirty(false)
    setViewMode('edit')
  }

  function selectSkill(skill) {
    if (dirty) {
      if (!confirm('You have unsaved changes. Discard?')) return
    }
    selectSkillDirect(skill)
  }

  function handleContentChange(val) {
    setContent(val)
    setDirty(true)
  }

  const handleSave = useCallback(async () => {
    if (!selectedSkill || !dirty) return
    setSaving(true)
    try {
      const res = await api.updateSkill(selectedSkill.id, { ...selectedSkill, content })
      const updated = res.data
      setSelectedSkill(updated)
      setSkills((prev) => prev.map((s) => (s.id === updated.id ? updated : s)))
      setDirty(false)
    } catch (err) {
      alert('Failed to save: ' + err.message)
    } finally {
      setSaving(false)
    }
  }, [selectedSkill, content, dirty])

  // Cmd+S
  useEffect(() => {
    function onKeyDown(e) {
      if ((e.metaKey || e.ctrlKey) && e.key === 's') {
        e.preventDefault()
        handleSave()
      }
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [handleSave])

  // Linting: debounced re-lint on content change
  useEffect(() => {
    if (viewMode !== 'edit') return
    clearTimeout(lintTimerRef.current)
    lintTimerRef.current = setTimeout(() => {
      setLintWarnings(lintContent(content))
    }, 500)
    return () => clearTimeout(lintTimerRef.current)
  }, [content, viewMode])

  // Load scheduler config when project loads
  useEffect(() => {
    if (!id) return
    api.getSchedulerConfig(id).then((r) => setScheduleConfig(r.data)).catch(() => {})
    api.getPendingOptimizations(id).then((r) => setPendingOpts(r.data || [])).catch(() => {})
  }, [id])

  // Optimize skill
  async function handleOptimize() {
    if (!selectedSkill) return
    setOptimizeStatus('running')
    setOptimizeOpen(true)
    try {
      const res = await api.optimizeSkill({ content, name: selectedSkill.name })
      setOptimizeResult(res.data?.result || res.data)
      setOptimizeStatus('done')
    } catch {
      setOptimizeStatus('idle')
      setOptimizeOpen(false)
    }
  }

  function applyOptimization() {
    if (!optimizeResult?.optimized_content) return
    setContent(optimizeResult.optimized_content)
    setDirty(true)
    setOptimizeOpen(false)
    setOptimizeResult(null)
    setOptimizeStatus('idle')
  }

  // Version history
  async function loadVersions() {
    if (!selectedSkill) return
    try {
      const res = await api.getVersions(selectedSkill.id)
      setVersions(res.data || [])
      setVersionsOpen(true)
    } catch {
      setVersions([])
    }
  }

  function restoreVersion(v) {
    setContent(v.content)
    setDirty(true)
    setVersionsOpen(false)
    setSelectedVersion(null)
  }

  // Playground
  async function runTest() {
    if (!testMessage.trim()) return
    setTestRunning(true)
    setTestResponse(null)
    try {
      const res = await api.testPrompt({ system_prompt: content, user_message: testMessage })
      setTestResponse(res)
    } catch (err) {
      setTestResponse({ error: err.message })
    } finally {
      setTestRunning(false)
    }
  }

  // Analytics
  async function loadAnalytics() {
    if (!selectedSkill) return
    try {
      const res = await api.getSkillAnalytics(selectedSkill.id)
      setAnalyticsData(res.data)
      setAnalyticsOpen(true)
    } catch {
      setAnalyticsData(null)
    }
  }

  // Scheduler
  async function toggleSchedule(enabled) {
    try {
      const res = await api.setSchedulerConfig(id, { enabled, frequency: scheduleConfig?.frequency || 'weekly' })
      setScheduleConfig(res.data)
    } catch {}
  }

  async function setScheduleFrequency(frequency) {
    try {
      const res = await api.setSchedulerConfig(id, { enabled: scheduleConfig?.enabled, frequency })
      setScheduleConfig(res.data)
    } catch {}
  }

  async function runSchedulerNow() {
    try {
      await api.runOptimization(id)
      const res = await api.getPendingOptimizations(id)
      setPendingOpts(res.data || [])
    } catch {}
  }

  // Has includes
  const hasIncludes = content.includes('{{include:')

  if (loading) {
    return (
      <div className="h-full flex items-center justify-center">
        <div className="animate-pulse-bar">
          <Loader className="w-6 h-6" style={{ color: '#888' }} />
        </div>
      </div>
    )
  }

  const tree = buildFileTree(skills)
  const breadcrumbs = getBreadcrumbs(selectedSkill, project?.name || 'Project')
  const tokenEstimate = Math.ceil((content?.length || 0) / 4)

  return (
    <div className="h-full flex flex-col" style={{ position: 'relative' }}>
      {/* Top bar: breadcrumbs + analysis pill + save */}
      <div
        className="flex items-center justify-between shrink-0"
        style={{ borderBottom: '1px solid #e5e5e5', padding: '0 16px', height: 44, background: '#fff', position: 'relative', zIndex: 21 }}
      >
        <div className="flex items-center gap-1 min-w-0">
          <button
            onClick={() => navigate('/')}
            style={{ padding: 4, background: 'none', border: 0, cursor: 'pointer', color: '#888', display: 'flex' }}
            title="Home"
          >
            <Home className="w-3.5 h-3.5" />
          </button>
          {breadcrumbs.map((crumb, i) => {
            const isLast = i === breadcrumbs.length - 1
            const isProjectName = i === 0
            const isClickable = !isLast
            return (
              <span key={i} className="flex items-center gap-1" style={{ fontSize: 12, color: isLast ? '#000' : '#888' }}>
                <ChevronRight className="w-3 h-3" style={{ color: '#ddd' }} />
                {isClickable ? (
                  <button
                    onClick={() => {
                      if (isProjectName) {
                        // Deselect file — show project root
                        if (dirty && !confirm('You have unsaved changes. Discard?')) return
                        setSelectedSkill(null)
                        setContent('')
                        setDirty(false)
                      }
                    }}
                    style={{
                      background: 'none',
                      border: 0,
                      cursor: 'pointer',
                      fontSize: 12,
                      fontWeight: 400,
                      color: '#888',
                      padding: 0,
                      textDecoration: 'none',
                    }}
                    onMouseEnter={(e) => { e.currentTarget.style.color = '#000' }}
                    onMouseLeave={(e) => { e.currentTarget.style.color = '#888' }}
                    className="truncate"
                  >
                    {crumb}
                  </button>
                ) : (
                  <span style={{ fontWeight: 600 }} className="truncate">{crumb}</span>
                )}
              </span>
            )
          })}
          {dirty && (
            <span style={{ fontSize: 10, color: '#D4A843', fontWeight: 500, marginLeft: 8 }}>Unsaved</span>
          )}
        </div>

        <div className="flex items-center gap-3">
          {/* Analysis pill */}
          <AnalysisPill
            status={analysisStatus}
            result={analysisResult}
            expanded={analysisExpanded}
            onToggle={() => setAnalysisExpanded(!analysisExpanded)}
          />

          {selectedSkill && (
            <>
              <span style={{ fontSize: 10, color: '#aaa', fontFamily: 'JetBrains Mono, monospace' }}>
                ~{tokenEstimate.toLocaleString()} tokens
              </span>

              {/* View mode toggle: icon-only square buttons */}
              <div className="flex" style={{ gap: 2 }}>
                {[
                  { mode: 'edit', Icon: PencilIcon, title: 'Edit' },
                  { mode: 'preview', Icon: EyeIcon, title: 'Preview' },
                  { mode: 'test', Icon: BeakerIcon, title: 'Test' },
                ].map(({ mode, Icon, title }) => (
                  <button
                    key={mode}
                    onClick={() => setViewMode(mode)}
                    title={title}
                    style={{
                      width: 28,
                      height: 28,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      border: '1px solid #e5e5e5',
                      borderRadius: 2,
                      cursor: 'pointer',
                      background: viewMode === mode ? '#000' : '#fff',
                    }}
                  >
                    <Icon color={viewMode === mode ? '#fff' : '#888'} />
                  </button>
                ))}
              </div>

              {/* Optimize button */}
              <button
                onClick={handleOptimize}
                disabled={optimizeStatus === 'running'}
                title="Optimize"
                style={{
                  width: 28, height: 28, display: 'flex', alignItems: 'center', justifyContent: 'center',
                  border: '1px solid #e5e5e5', borderRadius: 2, cursor: 'pointer',
                  background: optimizeStatus === 'running' ? '#f5f5f5' : '#fff',
                }}
              >
                {optimizeStatus === 'running'
                  ? <Loader className="w-3.5 h-3.5" style={{ color: '#888', animation: 'spin 1s linear infinite' }} />
                  : <Zap className="w-3.5 h-3.5" style={{ color: '#D4A843' }} />}
              </button>

              {/* History button */}
              <button
                onClick={loadVersions}
                title="Version history"
                style={{
                  width: 28, height: 28, display: 'flex', alignItems: 'center', justifyContent: 'center',
                  border: '1px solid #e5e5e5', borderRadius: 2, cursor: 'pointer', background: '#fff',
                }}
              >
                <Clock className="w-3.5 h-3.5" style={{ color: '#888' }} />
              </button>

              <button
                onClick={handleSave}
                disabled={saving || !dirty}
                className="btn-primary btn-sm"
                style={{ opacity: dirty ? 1 : 0.4 }}
              >
                <Save className="w-3.5 h-3.5" />
                {saving ? 'Saving...' : 'Save'}
              </button>
            </>
          )}
        </div>
      </div>

      {/* Analysis dropdown (overlays below breadcrumb bar) */}
      {analysisExpanded && analysisResult && (
        <AnalysisDropdown
          result={analysisResult}
          onClose={() => setAnalysisExpanded(false)}
          scheduleConfig={scheduleConfig}
          onToggleSchedule={toggleSchedule}
          onSetFrequency={setScheduleFrequency}
          onRunNow={runSchedulerNow}
          pendingCount={pendingOpts.length}
        />
      )}

      {/* Optimize panel */}
      {optimizeOpen && (
        <div className="animate-fade-in" style={{
          position: 'absolute', top: 44, left: 0, right: 0, zIndex: 19,
          background: '#fff', borderBottom: '1px solid #e5e5e5',
          boxShadow: '0 4px 16px rgba(0,0,0,0.08)', padding: '16px 20px', maxHeight: '50vh', overflowY: 'auto',
        }}>
          <div className="flex items-center justify-between" style={{ marginBottom: 12 }}>
            <div className="flex items-center gap-2">
              <Zap className="w-4 h-4" style={{ color: '#D4A843' }} />
              <span style={{ fontSize: 14, fontWeight: 600, color: '#000' }}>Optimization</span>
            </div>
            <button onClick={() => { setOptimizeOpen(false); setOptimizeResult(null); setOptimizeStatus('idle') }}
              style={{ fontSize: 11, color: '#888', background: 'none', border: 0, cursor: 'pointer' }}>Close</button>
          </div>
          {optimizeStatus === 'running' && (
            <div className="flex items-center gap-2" style={{ padding: 12, color: '#888', fontSize: 13 }}>
              <Loader className="w-4 h-4" style={{ animation: 'spin 1s linear infinite' }} /> Optimizing...
            </div>
          )}
          {optimizeStatus === 'done' && optimizeResult && (
            <>
              {optimizeResult.diff_summary?.token_change && (
                <div style={{ padding: '8px 12px', background: '#f5f5f5', borderRadius: 4, marginBottom: 12, fontSize: 12 }}>
                  <strong>Tokens:</strong> {optimizeResult.diff_summary.token_change.original_estimate} → {optimizeResult.diff_summary.token_change.optimized_estimate}
                  {optimizeResult.diff_summary.token_change.reduction_percent > 0 && (
                    <span style={{ color: '#D4A843', marginLeft: 8 }}>
                      ({optimizeResult.diff_summary.token_change.reduction_percent}% reduction)
                    </span>
                  )}
                </div>
              )}
              {optimizeResult.diff_summary?.changes_made?.length > 0 && (
                <div style={{ marginBottom: 12 }}>
                  {optimizeResult.diff_summary.changes_made.map((c, i) => (
                    <div key={i} style={{ padding: '6px 0', borderBottom: '1px solid #f0f0f0', fontSize: 12, color: '#333' }}>
                      <span className="badge-gray" style={{ fontSize: 9, marginRight: 6 }}>{c.type}</span>
                      {c.description}
                    </div>
                  ))}
                </div>
              )}
              <div className="flex gap-2">
                <button onClick={applyOptimization} className="btn-primary btn-sm">Apply Changes</button>
                <button onClick={() => { setOptimizeOpen(false); setOptimizeResult(null); setOptimizeStatus('idle') }}
                  className="btn-secondary btn-sm">Dismiss</button>
              </div>
            </>
          )}
        </div>
      )}

      {/* Version history panel */}
      {versionsOpen && (
        <div className="animate-fade-in" style={{
          position: 'absolute', top: 44, left: 0, right: 0, zIndex: 18,
          background: '#fff', borderBottom: '1px solid #e5e5e5',
          boxShadow: '0 4px 16px rgba(0,0,0,0.08)', padding: '16px 20px', maxHeight: '50vh', overflowY: 'auto',
        }}>
          <div className="flex items-center justify-between" style={{ marginBottom: 12 }}>
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4" style={{ color: '#888' }} />
              <span style={{ fontSize: 14, fontWeight: 600, color: '#000' }}>Version History</span>
            </div>
            <button onClick={() => { setVersionsOpen(false); setSelectedVersion(null) }}
              style={{ fontSize: 11, color: '#888', background: 'none', border: 0, cursor: 'pointer' }}>Close</button>
          </div>
          {versions.length === 0 ? (
            <p style={{ fontSize: 12, color: '#aaa' }}>No version history yet.</p>
          ) : (
            versions.map((v) => (
              <div key={v.id} style={{ padding: '8px 0', borderBottom: '1px solid #f0f0f0' }}>
                <div className="flex items-center justify-between">
                  <div>
                    <span style={{ fontSize: 12, fontWeight: 600, color: '#000' }}>v{v.version}</span>
                    <span style={{ fontSize: 11, color: '#888', marginLeft: 8 }}>{v.change_summary}</span>
                    <span style={{ fontSize: 10, color: '#aaa', marginLeft: 8 }}>
                      {new Date(v.created_at).toLocaleDateString()}
                    </span>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => setSelectedVersion(selectedVersion?.id === v.id ? null : v)}
                      className="btn-ghost btn-sm" style={{ fontSize: 10 }}
                    >{selectedVersion?.id === v.id ? 'Hide diff' : 'Diff'}</button>
                    <button onClick={() => restoreVersion(v)} className="btn-secondary btn-sm" style={{ fontSize: 10 }}>Restore</button>
                  </div>
                </div>
                {selectedVersion?.id === v.id && (
                  <div style={{ marginTop: 8, maxHeight: 200, overflowY: 'auto', fontFamily: 'JetBrains Mono, monospace', fontSize: 11 }}>
                    {simpleDiff(v.content, content).map((d, i) => (
                      <div key={i} className={d.type === 'add' ? 'diff-add' : 'diff-remove'}>
                        {d.type === 'add' ? '+ ' : '- '}{d.text}
                      </div>
                    ))}
                    {simpleDiff(v.content, content).length === 0 && (
                      <p style={{ color: '#aaa', padding: 8 }}>No differences.</p>
                    )}
                  </div>
                )}
              </div>
            ))
          )}
        </div>
      )}

      {/* Main area: tree + editor */}
      <div className="flex-1 flex overflow-hidden" style={{ position: 'relative' }}>
        {/* Left: File Tree */}
        <div
          className="shrink-0 overflow-y-auto"
          style={{
            width: 220,
            borderRight: '1px solid #e5e5e5',
            background: '#fafafa',
            padding: '8px 0',
          }}
        >
          {/* Project header */}
          <div style={{ padding: '6px 12px 10px', borderBottom: '1px solid #e5e5e5', marginBottom: 4 }}>
            <div className="flex items-center gap-2">
              <FolderOpen className="w-3.5 h-3.5" style={{ color: '#888' }} />
              <span style={{ fontSize: 12, fontWeight: 600, color: '#000' }} className="truncate">
                {project?.name}
              </span>
            </div>
            {project?.description && (
              <p style={{ fontSize: 10, color: '#888', marginTop: 2, paddingLeft: 18 }} className="truncate">
                {project.description}
              </p>
            )}
          </div>

          {/* Tree */}
          {skills.length === 0 ? (
            <p style={{ padding: '12px 16px', fontSize: 12, color: '#aaa' }}>No files yet</p>
          ) : (
            Object.entries(tree).map(([name, node]) => (
              <TreeNode
                key={name}
                name={name}
                node={node}
                selectedId={selectedSkill?.id}
                onSelect={selectSkill}
              />
            ))
          )}
        </div>

        {/* Center: Editor / Preview / Test */}
        <div className="flex-1 flex flex-col min-w-0 overflow-hidden" style={{ position: 'relative' }}>
          {!selectedSkill ? (
            <div className="flex-1 flex items-center justify-center">
              <div style={{ textAlign: 'center', color: '#aaa' }}>
                <FileText className="w-10 h-10 mx-auto" style={{ opacity: 0.3, marginBottom: 8 }} />
                <p style={{ fontSize: 14 }}>Select a file to edit</p>
              </div>
            </div>
          ) : viewMode === 'preview' ? (
            <div className="flex-1 overflow-y-auto" style={{ padding: 24 }}>
              {/* Resolve includes visually in preview */}
              <MarkdownPreview content={content} />
              {hasIncludes && (
                <div style={{ marginTop: 16, padding: '8px 12px', background: '#f0f0f0', borderRadius: 4, fontSize: 11, color: '#666' }}>
                  This skill uses <code className="include-tag">{'{{include:...}}'}</code> syntax. Includes are resolved when served via the API.
                </div>
              )}
            </div>
          ) : viewMode === 'test' ? (
            /* ── Playground / Test Mode ── */
            <div className="flex-1 flex flex-col overflow-hidden">
              {/* System prompt (readonly) */}
              <div style={{ flex: '0 0 auto', maxHeight: '30%', overflowY: 'auto', padding: '12px 16px', background: '#fafafa', borderBottom: '1px solid #e5e5e5' }}>
                <div style={{ fontSize: 10, fontWeight: 600, color: '#888', textTransform: 'uppercase', marginBottom: 6 }}>System Prompt</div>
                <pre style={{ fontSize: 12, fontFamily: 'JetBrains Mono, monospace', color: '#333', whiteSpace: 'pre-wrap', margin: 0, lineHeight: 1.6 }}>
                  {content?.slice(0, 1000)}{content?.length > 1000 ? '...' : ''}
                </pre>
              </div>

              {/* User message input + response */}
              <div className="flex-1 flex flex-col overflow-hidden" style={{ padding: 16 }}>
                <div style={{ fontSize: 10, fontWeight: 600, color: '#888', textTransform: 'uppercase', marginBottom: 6 }}>User Message</div>
                <textarea
                  value={testMessage}
                  onChange={(e) => setTestMessage(e.target.value)}
                  placeholder="Type a test message..."
                  className="input"
                  style={{ minHeight: 60, maxHeight: 100, resize: 'vertical', fontFamily: 'JetBrains Mono, monospace', fontSize: 12, marginBottom: 8 }}
                />
                <div className="flex items-center gap-3" style={{ marginBottom: 12 }}>
                  <button onClick={runTest} disabled={testRunning || !testMessage.trim()} className="btn-primary btn-sm"
                    style={{ opacity: testRunning || !testMessage.trim() ? 0.4 : 1 }}>
                    {testRunning ? <><Loader className="w-3 h-3" style={{ animation: 'spin 1s linear infinite' }} /> Running...</> : 'Run'}
                  </button>
                  {testResponse?.usage && (
                    <span style={{ fontSize: 10, color: '#aaa', fontFamily: 'JetBrains Mono, monospace' }}>
                      {testResponse.usage.input_tokens}+{testResponse.usage.output_tokens} tokens
                    </span>
                  )}
                </div>

                {/* Response area */}
                {testResponse && (
                  <div className="flex-1 overflow-y-auto" style={{
                    padding: 12, background: testResponse.error ? '#fdf5f5' : '#fafafa',
                    border: '1px solid #e5e5e5', borderRadius: 4,
                  }}>
                    {testResponse.error ? (
                      <p style={{ fontSize: 12, color: '#c44' }}>{testResponse.error}</p>
                    ) : (
                      <div className="markdown-preview" style={{ fontSize: 13 }}>
                        <MarkdownPreview content={testResponse.response || ''} />
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          ) : (
            /* ── Edit Mode ── */
            <div className="flex-1 flex flex-col overflow-hidden">
              {/* Includes info bar */}
              {hasIncludes && (
                <div style={{ padding: '6px 12px', background: '#f8f8f5', borderBottom: '1px solid #e8e5d8', fontSize: 11, color: '#8a7340', flexShrink: 0 }}>
                  This skill uses <strong>{'{{include:...}}'}</strong> syntax. Includes are resolved when served via API.
                </div>
              )}
              <textarea
                value={content}
                onChange={(e) => handleContentChange(e.target.value)}
                className="skill-editor w-full h-full flex-1"
                spellCheck={false}
                style={{ resize: 'none' }}
              />
              {/* Lint warnings bar */}
              {lintWarnings.length > 0 && (
                <div className="lint-bar">
                  <AlertTriangle className="w-3 h-3 shrink-0" style={{ color: '#D4A843' }} />
                  {lintWarnings.map((w, i) => (
                    <span key={i} className="lint-pill">{w.msg}</span>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Floating toolbar (right side) */}
          {selectedSkill && (
            <div style={{ position: 'absolute', right: 16, top: 16, zIndex: 10 }}>
              <div style={{
                display: 'flex', flexDirection: 'column', gap: 2,
                background: '#fff', border: '1px solid #e5e5e5', borderRadius: 8, padding: 4,
                boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
              }}>
                <FloatingToolbar skill={selectedSkill} />
                {/* Analytics button */}
                <button
                  onClick={loadAnalytics}
                  title="Usage Analytics"
                  style={{
                    width: 32, height: 32, display: 'flex', alignItems: 'center', justifyContent: 'center',
                    border: 0, borderRadius: 6, background: analyticsOpen ? '#f0f0f0' : 'transparent',
                    cursor: 'pointer', color: analyticsOpen ? '#000' : '#888', transition: 'all 80ms',
                  }}
                  onMouseEnter={(e) => { e.currentTarget.style.background = '#f0f0f0' }}
                  onMouseLeave={(e) => { if (!analyticsOpen) e.currentTarget.style.background = 'transparent' }}
                >
                  <BarChart2 className="w-4 h-4" />
                </button>
              </div>

              {/* Analytics popover */}
              {analyticsOpen && (
                <div className="animate-fade-in" style={{
                  position: 'absolute', right: 44, top: 0, width: 280,
                  background: '#fff', border: '1px solid #e5e5e5', borderRadius: 8, padding: 14,
                  boxShadow: '0 4px 16px rgba(0,0,0,0.1)',
                }}>
                  <div className="flex items-center justify-between" style={{ marginBottom: 10 }}>
                    <span style={{ fontSize: 12, fontWeight: 600, color: '#000' }}>Usage Analytics</span>
                    <button onClick={() => setAnalyticsOpen(false)}
                      style={{ fontSize: 10, color: '#888', background: 'none', border: 0, cursor: 'pointer' }}>Close</button>
                  </div>
                  {analyticsData ? (
                    <>
                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8, marginBottom: 12 }}>
                        <div style={{ textAlign: 'center', padding: 8, background: '#f5f5f5', borderRadius: 4 }}>
                          <div style={{ fontSize: 18, fontWeight: 700 }}>{analyticsData.total || 0}</div>
                          <div style={{ fontSize: 9, color: '#888' }}>Total Hits</div>
                        </div>
                        <div style={{ textAlign: 'center', padding: 8, background: '#f5f5f5', borderRadius: 4 }}>
                          <div style={{ fontSize: 18, fontWeight: 700 }}>{Object.keys(analyticsData.models || {}).length}</div>
                          <div style={{ fontSize: 9, color: '#888' }}>Models</div>
                        </div>
                        <div style={{ textAlign: 'center', padding: 8, background: '#f5f5f5', borderRadius: 4 }}>
                          <div style={{ fontSize: 18, fontWeight: 700 }}>{Object.keys(analyticsData.agents || {}).length}</div>
                          <div style={{ fontSize: 9, color: '#888' }}>Agents</div>
                        </div>
                      </div>
                      {/* Daily bars (last 7 days) */}
                      {analyticsData.daily && Object.keys(analyticsData.daily).length > 0 && (
                        <div>
                          <div style={{ fontSize: 10, fontWeight: 600, color: '#888', marginBottom: 6 }}>Daily Access</div>
                          {Object.entries(analyticsData.daily).slice(-7).map(([day, count]) => {
                            const maxCount = Math.max(...Object.values(analyticsData.daily).slice(-7))
                            const pct = maxCount > 0 ? (count / maxCount) * 100 : 0
                            return (
                              <div key={day} className="flex items-center gap-2" style={{ marginBottom: 3 }}>
                                <span style={{ fontSize: 9, color: '#aaa', width: 50, flexShrink: 0 }}>{day.slice(5)}</span>
                                <div style={{ flex: 1, height: 6, background: '#f0f0f0', borderRadius: 3 }}>
                                  <div style={{ height: '100%', width: `${pct}%`, background: '#000', borderRadius: 3 }} />
                                </div>
                                <span style={{ fontSize: 9, color: '#888', width: 20, textAlign: 'right' }}>{count}</span>
                              </div>
                            )
                          })}
                        </div>
                      )}
                      {(!analyticsData.daily || Object.keys(analyticsData.daily).length === 0) && (
                        <p style={{ fontSize: 11, color: '#aaa' }}>No usage data yet. Share the API endpoint to start tracking.</p>
                      )}
                    </>
                  ) : (
                    <p style={{ fontSize: 11, color: '#aaa' }}>Loading...</p>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
