import { useState, useEffect, useCallback, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  ChevronRight,
  ChevronDown,
  FileText,
  FolderOpen,
  Home,
  Save,
  Globe,
  Cpu,
  Terminal,
  Copy,
  Check,
  Sparkles,
  Loader,
  AlertTriangle,
  Zap,
} from 'lucide-react'
import { api } from '../api'
import MarkdownPreview from '../components/MarkdownPreview'

// ── Helpers ──────────────────────────────────────────────

function buildFileTree(skills) {
  const root = {}
  for (const skill of skills) {
    const path = skill.tags?.[0] || skill.name
    const parts = path.split('/')
    let node = root
    for (let i = 0; i < parts.length - 1; i++) {
      if (!node[parts[i]]) node[parts[i]] = { __children: {} }
      if (!node[parts[i]].__children) node[parts[i]].__children = {}
      node = node[parts[i]].__children
    }
    const filename = parts[parts.length - 1]
    node[filename] = { __skill: skill }
  }
  return root
}

function getBreadcrumbs(skill, projectName) {
  if (!skill) return [projectName]
  const path = skill.tags?.[0] || skill.name
  return [projectName, ...path.split('/')]
}

function CopyButton({ text }) {
  const [copied, setCopied] = useState(false)
  const handleCopy = async () => {
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }
  return (
    <button
      onClick={handleCopy}
      style={{ padding: 4, background: 'transparent', border: 0, cursor: 'pointer', color: copied ? '#000' : '#aaa', display: 'flex' }}
      title="Copy"
    >
      {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
    </button>
  )
}

// Format analysis result as a markdown document
function formatAnalysisMarkdown(analysis, projectName, skills) {
  const lines = []
  lines.push(`# doso analysis: ${projectName}`)
  lines.push('')
  lines.push(`*Auto-generated by doso.dev on ${new Date().toLocaleDateString()}*`)
  lines.push('')

  if (analysis.project_summary) {
    lines.push('## Project Overview')
    lines.push('')
    lines.push(analysis.project_summary)
    lines.push('')
  }

  if (analysis.skill_summaries?.length > 0) {
    lines.push('## Skills')
    lines.push('')
    for (const s of analysis.skill_summaries) {
      lines.push(`### ${s.name}`)
      lines.push(s.purpose || '')
      if (s.strengths?.length > 0) {
        lines.push(`- **Strengths:** ${s.strengths.join(', ')}`)
      }
      if (s.weaknesses?.length > 0) {
        lines.push(`- **Weaknesses:** ${s.weaknesses.join(', ')}`)
      }
      lines.push('')
    }
  }

  const score = analysis.health_score
  if (score) {
    lines.push('## Health Score')
    lines.push('')
    lines.push(`**Overall: ${score.overall}/100**`)
    if (score.breakdown) {
      lines.push(`- Clarity: ${score.breakdown.clarity}/100`)
      lines.push(`- Consistency: ${score.breakdown.consistency}/100`)
      lines.push(`- Coverage: ${score.breakdown.coverage}/100`)
      lines.push(`- Efficiency: ${score.breakdown.efficiency}/100`)
    }
    if (score.summary) lines.push(`\n${score.summary}`)
    lines.push('')
  }

  if (analysis.suggestions?.length > 0) {
    lines.push('## Improvement Suggestions')
    lines.push('')
    for (const s of analysis.suggestions) {
      const priority = s.priority === 'high' ? '!!!' : s.priority === 'medium' ? '!!' : '!'
      lines.push(`### ${priority} ${s.title}`)
      if (s.skill_name) lines.push(`*Applies to: ${s.skill_name}*`)
      lines.push('')
      lines.push(s.description)
      lines.push('')
    }
  }

  if (analysis.coverage_gaps?.length > 0) {
    lines.push('## Coverage Gaps')
    lines.push('')
    for (const g of analysis.coverage_gaps) {
      lines.push(`- **${g.gap}**: ${g.suggestion}`)
    }
    lines.push('')
  }

  if (analysis.cross_skill_contradictions?.length > 0) {
    lines.push('## Contradictions')
    lines.push('')
    for (const c of analysis.cross_skill_contradictions) {
      lines.push(`- **${c.skill_a} vs ${c.skill_b}** (${c.severity}): ${c.description}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

// ── File Tree Component ──────────────────────────────────

function TreeNode({ name, node, depth = 0, selectedId, onSelect }) {
  const [open, setOpen] = useState(true)

  if (node.__skill) {
    const skill = node.__skill
    const isSelected = selectedId === skill.id
    const isDoso = name === 'doso_readme' || name === 'doso_readme.md'
    return (
      <button
        onClick={() => onSelect(skill)}
        className="w-full text-left flex items-center gap-1.5"
        style={{
          padding: '5px 8px',
          paddingLeft: 8 + depth * 16,
          fontSize: 12,
          color: isSelected ? '#000' : isDoso ? '#D4A843' : '#555',
          fontWeight: isSelected ? 600 : 400,
          fontStyle: isDoso ? 'italic' : 'normal',
          background: isSelected ? '#f0f0f0' : 'transparent',
          border: 0,
          borderRadius: 3,
          cursor: 'pointer',
          transition: 'background 80ms',
        }}
        onMouseEnter={(e) => { if (!isSelected) e.currentTarget.style.background = '#f5f5f5' }}
        onMouseLeave={(e) => { if (!isSelected) e.currentTarget.style.background = 'transparent' }}
      >
        {isDoso ? (
          <Sparkles className="w-3.5 h-3.5 shrink-0" style={{ color: '#D4A843' }} />
        ) : (
          <FileText className="w-3.5 h-3.5 shrink-0" style={{ color: '#D4A843' }} />
        )}
        <span className="truncate">{name}</span>
      </button>
    )
  }

  // Directory node
  const children = node.__children || node
  const entries = Object.entries(children).filter(([k]) => k !== '__children')
  if (entries.length === 0) return null

  return (
    <div>
      <button
        onClick={() => setOpen(!open)}
        className="w-full text-left flex items-center gap-1.5"
        style={{
          padding: '5px 8px',
          paddingLeft: 8 + depth * 16,
          fontSize: 12,
          color: '#666',
          fontWeight: 500,
          background: 'transparent',
          border: 0,
          cursor: 'pointer',
        }}
      >
        {open ? <ChevronDown className="w-3 h-3 shrink-0" /> : <ChevronRight className="w-3 h-3 shrink-0" />}
        <FolderOpen className="w-3.5 h-3.5 shrink-0" style={{ color: '#888' }} />
        <span className="truncate">{name}</span>
      </button>
      {open && entries.map(([key, child]) => (
        <TreeNode
          key={key}
          name={key}
          node={child}
          depth={depth + 1}
          selectedId={selectedId}
          onSelect={onSelect}
        />
      ))}
    </div>
  )
}

// ── Floating Toolbar ──────────────────────────────────────

function FloatingToolbar({ skill }) {
  const [openPanel, setOpenPanel] = useState(null)

  if (!skill?.id) return null

  const base = window.location.origin
  const panels = [
    {
      key: 'api',
      icon: Globe,
      label: 'REST API',
      url: `${base}/api/v1/skills/${skill.id}`,
      desc: 'Full skill object as JSON',
    },
    {
      key: 'mcp',
      icon: Cpu,
      label: 'MCP Resource',
      url: `${base}/api/v1/mcp/skills/${skill.id}`,
      desc: 'MCP-compatible resource format',
    },
    {
      key: 'raw',
      icon: Terminal,
      label: 'Raw Markdown',
      url: `${base}/api/v1/skills/${skill.id}/raw`,
      desc: 'Plain text — paste in your agent',
    },
  ]

  return (
    <div style={{ position: 'absolute', right: 16, top: 16, zIndex: 10 }}>
      {/* Icon buttons */}
      <div style={{
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        background: '#fff',
        border: '1px solid #e5e5e5',
        borderRadius: 8,
        padding: 4,
        boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
      }}>
        {panels.map((p) => (
          <button
            key={p.key}
            onClick={() => setOpenPanel(openPanel === p.key ? null : p.key)}
            title={p.label}
            style={{
              width: 32,
              height: 32,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              border: 0,
              borderRadius: 6,
              background: openPanel === p.key ? '#f0f0f0' : 'transparent',
              cursor: 'pointer',
              color: openPanel === p.key ? '#000' : '#888',
              transition: 'all 80ms',
            }}
            onMouseEnter={(e) => { e.currentTarget.style.background = '#f0f0f0' }}
            onMouseLeave={(e) => { if (openPanel !== p.key) e.currentTarget.style.background = 'transparent' }}
          >
            <p.icon className="w-4 h-4" />
          </button>
        ))}
      </div>

      {/* Popover panel */}
      {openPanel && (() => {
        const p = panels.find((x) => x.key === openPanel)
        if (!p) return null
        return (
          <div
            className="animate-fade-in"
            style={{
              position: 'absolute',
              right: 44,
              top: 0,
              width: 300,
              background: '#fff',
              border: '1px solid #e5e5e5',
              borderRadius: 8,
              padding: 14,
              boxShadow: '0 4px 16px rgba(0,0,0,0.1)',
            }}
          >
            <div className="flex items-center justify-between" style={{ marginBottom: 8 }}>
              <span style={{ fontSize: 12, fontWeight: 600, color: '#000' }}>{p.label}</span>
              <CopyButton text={p.url} />
            </div>
            <div style={{
              padding: '8px 10px',
              background: '#f5f5f5',
              borderRadius: 4,
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 11,
              color: '#333',
              wordBreak: 'break-all',
              lineHeight: 1.5,
            }}>
              <span style={{ background: '#000', color: '#fff', padding: '1px 5px', borderRadius: 2, fontSize: 10, fontWeight: 700, marginRight: 6 }}>GET</span>
              {p.url}
            </div>
            <p style={{ fontSize: 11, color: '#888', marginTop: 8 }}>{p.desc}</p>
          </div>
        )
      })()}
    </div>
  )
}

// ── Analysis Pill (in breadcrumb bar) ─────────────────────

function AnalysisPill({ status, result, onToggle, expanded }) {
  if (status === 'idle') return null

  return (
    <button
      onClick={status === 'done' || status === 'error' ? onToggle : undefined}
      className="flex items-center gap-2"
      style={{
        padding: '4px 12px',
        borderRadius: 100,
        background: status === 'running' ? '#f5f3ee' : status === 'done' ? '#f0f0f0' : '#f5f5f5',
        border: '1px solid',
        borderColor: status === 'running' ? '#e8e0d0' : '#e5e5e5',
        cursor: status === 'done' || status === 'error' ? 'pointer' : 'default',
        fontSize: 11,
        color: status === 'running' ? '#8a7340' : '#555',
        fontWeight: 500,
        whiteSpace: 'nowrap',
        transition: 'all 150ms',
        position: 'relative',
        overflow: 'hidden',
      }}
    >
      {/* Progress bar background for running state */}
      {status === 'running' && (
        <div style={{
          position: 'absolute',
          left: 0,
          top: 0,
          bottom: 0,
          background: 'linear-gradient(90deg, #ece4d4 0%, #f5f0e5 50%, #ece4d4 100%)',
          backgroundSize: '200% 100%',
          animation: 'shimmer 1.5s ease-in-out infinite',
          width: '100%',
          borderRadius: 100,
        }} />
      )}

      <span style={{ position: 'relative', display: 'flex', alignItems: 'center', gap: 6 }}>
        {status === 'running' && (
          <>
            <Loader className="w-3 h-3" style={{ animation: 'spin 1s linear infinite' }} />
            Analyzing skills...
          </>
        )}
        {status === 'done' && (
          <>
            <Sparkles className="w-3 h-3" style={{ color: '#D4A843' }} />
            {result?.suggestions?.length > 0
              ? `${result.suggestions.length} suggestion${result.suggestions.length !== 1 ? 's' : ''}`
              : 'Analysis complete'}
            {result?.health_score?.overall != null && (
              <span style={{ color: '#aaa', fontWeight: 400 }}>
                &middot; {result.health_score.overall}/100
              </span>
            )}
          </>
        )}
        {status === 'error' && (
          <>
            <AlertTriangle className="w-3 h-3" style={{ color: '#aaa' }} />
            Analysis unavailable
          </>
        )}
      </span>
    </button>
  )
}

// ── Analysis Dropdown Panel ───────────────────────────────

function AnalysisDropdown({ result, onClose }) {
  if (!result) return null

  const analysis = result

  return (
    <div
      className="animate-fade-in"
      style={{
        position: 'absolute',
        top: 44,
        left: 0,
        right: 0,
        zIndex: 20,
        background: '#fff',
        borderBottom: '1px solid #e5e5e5',
        boxShadow: '0 4px 16px rgba(0,0,0,0.08)',
        maxHeight: '60vh',
        overflowY: 'auto',
        padding: '16px 20px',
      }}
    >
      <div className="flex items-center justify-between" style={{ marginBottom: 16 }}>
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4" style={{ color: '#D4A843' }} />
          <span style={{ fontSize: 14, fontWeight: 600, color: '#000' }}>Skill Analysis</span>
          {analysis.health_score?.overall != null && (
            <span className="badge-gray" style={{ fontSize: 10 }}>
              Health: {analysis.health_score.overall}/100
            </span>
          )}
        </div>
        <button
          onClick={onClose}
          style={{ fontSize: 11, color: '#888', background: 'none', border: 0, cursor: 'pointer', padding: '4px 8px' }}
        >
          Close
        </button>
      </div>

      {/* Project summary */}
      {analysis.project_summary && (
        <div style={{ padding: '10px 14px', background: '#fafafa', borderRadius: 6, marginBottom: 16, fontSize: 13, color: '#333', lineHeight: 1.6 }}>
          {analysis.project_summary}
        </div>
      )}

      {/* Suggestions */}
      {analysis.suggestions?.length > 0 && (
        <div style={{ marginBottom: 16 }}>
          <h4 style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
            Improvement Suggestions
          </h4>
          <div className="space-y-2">
            {analysis.suggestions.map((s, i) => (
              <div key={i} style={{ padding: '10px 14px', background: '#f5f5f5', borderRadius: 6, borderLeft: `3px solid ${s.priority === 'high' ? '#D4A843' : s.priority === 'medium' ? '#ddd' : '#eee'}` }}>
                <div className="flex items-center gap-2" style={{ marginBottom: 4 }}>
                  <Zap className="w-3 h-3 shrink-0" style={{ color: '#D4A843' }} />
                  <span style={{ fontSize: 12, fontWeight: 600, color: '#000' }}>{s.title}</span>
                  {s.skill_name && <span className="badge-gray" style={{ fontSize: 9 }}>{s.skill_name}</span>}
                  {s.category && <span className="badge-ochre" style={{ fontSize: 9 }}>{s.category}</span>}
                </div>
                <p style={{ fontSize: 12, color: '#555', lineHeight: 1.5, paddingLeft: 18 }}>{s.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Coverage gaps */}
      {analysis.coverage_gaps?.length > 0 && (
        <div style={{ marginBottom: 16 }}>
          <h4 style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
            Coverage Gaps
          </h4>
          {analysis.coverage_gaps.map((g, i) => (
            <div key={i} className="flex items-start gap-2" style={{ marginBottom: 6 }}>
              <AlertTriangle className="w-3 h-3 shrink-0" style={{ color: '#D4A843', marginTop: 2 }} />
              <span style={{ fontSize: 12, color: '#333', lineHeight: 1.5 }}>
                <strong>{g.gap}:</strong> {g.suggestion}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* Contradictions */}
      {analysis.cross_skill_contradictions?.length > 0 && (
        <div>
          <h4 style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
            Contradictions
          </h4>
          {analysis.cross_skill_contradictions.map((c, i) => (
            <div key={i} className="flex items-start gap-2" style={{ marginBottom: 6 }}>
              <AlertTriangle className="w-3 h-3 shrink-0" style={{ color: '#c44', marginTop: 2 }} />
              <span style={{ fontSize: 12, color: '#333', lineHeight: 1.5 }}>
                <strong>{c.skill_a} vs {c.skill_b}</strong> ({c.severity}): {c.description}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* Health breakdown */}
      {analysis.health_score?.breakdown && (
        <div style={{ marginTop: 16, paddingTop: 12, borderTop: '1px solid #f0f0f0' }}>
          <h4 style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
            Health Breakdown
          </h4>
          <div className="grid grid-cols-4 gap-3">
            {Object.entries(analysis.health_score.breakdown).map(([key, val]) => (
              <div key={key} style={{ textAlign: 'center' }}>
                <div style={{ fontSize: 18, fontWeight: 700, color: '#000' }}>{val}</div>
                <div style={{ fontSize: 10, color: '#888', textTransform: 'capitalize' }}>{key}</div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// ── Main ProjectView ──────────────────────────────────────

export default function ProjectView() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [project, setProject] = useState(null)
  const [skills, setSkills] = useState([])
  const [selectedSkill, setSelectedSkill] = useState(null)
  const [content, setContent] = useState('')
  const [dirty, setDirty] = useState(false)
  const [saving, setSaving] = useState(false)
  const [loading, setLoading] = useState(true)
  const [viewMode, setViewMode] = useState('edit') // edit | preview

  // Analysis state
  const [analysisStatus, setAnalysisStatus] = useState('idle')
  const [analysisResult, setAnalysisResult] = useState(null)
  const [analysisExpanded, setAnalysisExpanded] = useState(false)
  const analysisRanRef = useRef(false)

  useEffect(() => {
    loadProject()
  }, [id])

  async function loadProject() {
    try {
      const res = await api.getProject(id)
      const data = res.data
      setProject(data)
      setSkills(data.skills || [])

      // Select first skill by default
      if (data.skills?.length > 0) {
        selectSkillDirect(data.skills[0])
      }
    } catch (err) {
      console.error('Failed to load project:', err)
      navigate('/')
    } finally {
      setLoading(false)
    }
  }

  // Auto-start analysis once project loads
  useEffect(() => {
    if (skills.length === 0 || analysisRanRef.current) return
    analysisRanRef.current = true
    runAnalysis(skills)
  }, [skills])

  async function runAnalysis(skillList) {
    setAnalysisStatus('running')
    try {
      const payload = {
        skills: skillList.map((s) => ({ id: s.id, name: s.name, content: s.content })),
      }
      const res = await api.analyzeProject(payload)
      const data = res.data
      const analysis = data.analysis || data

      setAnalysisResult(analysis)
      setAnalysisStatus('done')

      // Create doso_readme document from analysis
      createDosoReadme(analysis, skillList)
    } catch {
      setAnalysisStatus('error')
    }
  }

  async function createDosoReadme(analysis, skillList) {
    try {
      const markdownContent = formatAnalysisMarkdown(analysis, project?.name || 'Project', skillList)
      const res = await api.createSkill({
        name: 'doso_readme',
        description: 'Auto-generated project analysis by doso.dev',
        content: markdownContent,
        category: 'General',
        tags: ['doso_readme', 'analysis'],
        is_public: false,
        project_id: id,
      })

      // Add to the project's skill list
      const newSkill = res.data
      if (newSkill?.id) {
        // Link it to the project
        try {
          await api.addSkillToProject(id, newSkill.id)
        } catch {
          // ignore if linking fails
        }
        setSkills((prev) => [...prev, newSkill])
      }
    } catch (err) {
      console.error('Failed to create doso_readme:', err)
    }
  }

  function selectSkillDirect(skill) {
    setSelectedSkill(skill)
    setContent(skill.content || '')
    setDirty(false)
    setViewMode('edit')
  }

  function selectSkill(skill) {
    if (dirty) {
      if (!confirm('You have unsaved changes. Discard?')) return
    }
    selectSkillDirect(skill)
  }

  function handleContentChange(val) {
    setContent(val)
    setDirty(true)
  }

  const handleSave = useCallback(async () => {
    if (!selectedSkill || !dirty) return
    setSaving(true)
    try {
      const res = await api.updateSkill(selectedSkill.id, { ...selectedSkill, content })
      const updated = res.data
      setSelectedSkill(updated)
      setSkills((prev) => prev.map((s) => (s.id === updated.id ? updated : s)))
      setDirty(false)
    } catch (err) {
      alert('Failed to save: ' + err.message)
    } finally {
      setSaving(false)
    }
  }, [selectedSkill, content, dirty])

  // Cmd+S
  useEffect(() => {
    function onKeyDown(e) {
      if ((e.metaKey || e.ctrlKey) && e.key === 's') {
        e.preventDefault()
        handleSave()
      }
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [handleSave])

  if (loading) {
    return (
      <div className="h-full flex items-center justify-center">
        <div className="animate-pulse-bar">
          <Loader className="w-6 h-6" style={{ color: '#888' }} />
        </div>
      </div>
    )
  }

  const tree = buildFileTree(skills)
  const breadcrumbs = getBreadcrumbs(selectedSkill, project?.name || 'Project')
  const tokenEstimate = Math.ceil((content?.length || 0) / 4)

  return (
    <div className="h-full flex flex-col" style={{ position: 'relative' }}>
      {/* Top bar: breadcrumbs + analysis pill + save */}
      <div
        className="flex items-center justify-between shrink-0"
        style={{ borderBottom: '1px solid #e5e5e5', padding: '0 16px', height: 44, background: '#fff', position: 'relative', zIndex: 21 }}
      >
        <div className="flex items-center gap-1 min-w-0">
          <button
            onClick={() => navigate('/')}
            style={{ padding: 4, background: 'none', border: 0, cursor: 'pointer', color: '#888', display: 'flex' }}
            title="Home"
          >
            <Home className="w-3.5 h-3.5" />
          </button>
          {breadcrumbs.map((crumb, i) => (
            <span key={i} className="flex items-center gap-1" style={{ fontSize: 12, color: i === breadcrumbs.length - 1 ? '#000' : '#888' }}>
              <ChevronRight className="w-3 h-3" style={{ color: '#ddd' }} />
              <span style={{ fontWeight: i === breadcrumbs.length - 1 ? 600 : 400 }} className="truncate">{crumb}</span>
            </span>
          ))}
          {dirty && (
            <span style={{ fontSize: 10, color: '#D4A843', fontWeight: 500, marginLeft: 8 }}>Unsaved</span>
          )}
        </div>

        <div className="flex items-center gap-3">
          {/* Analysis pill */}
          <AnalysisPill
            status={analysisStatus}
            result={analysisResult}
            expanded={analysisExpanded}
            onToggle={() => setAnalysisExpanded(!analysisExpanded)}
          />

          {selectedSkill && (
            <>
              <span style={{ fontSize: 10, color: '#aaa', fontFamily: 'JetBrains Mono, monospace' }}>
                ~{tokenEstimate.toLocaleString()} tokens
              </span>
              <div className="flex" style={{ border: '1px solid #e5e5e5', borderRadius: 4, overflow: 'hidden' }}>
                <button
                  onClick={() => setViewMode('edit')}
                  style={{
                    padding: '4px 10px', fontSize: 11, fontWeight: 500, border: 0, cursor: 'pointer',
                    background: viewMode === 'edit' ? '#000' : '#fff',
                    color: viewMode === 'edit' ? '#fff' : '#888',
                  }}
                >
                  Edit
                </button>
                <button
                  onClick={() => setViewMode('preview')}
                  style={{
                    padding: '4px 10px', fontSize: 11, fontWeight: 500, border: 0, cursor: 'pointer',
                    background: viewMode === 'preview' ? '#000' : '#fff',
                    color: viewMode === 'preview' ? '#fff' : '#888',
                    borderLeft: '1px solid #e5e5e5',
                  }}
                >
                  Preview
                </button>
              </div>
              <button
                onClick={handleSave}
                disabled={saving || !dirty}
                className="btn-primary btn-sm"
                style={{ opacity: dirty ? 1 : 0.4 }}
              >
                <Save className="w-3.5 h-3.5" />
                {saving ? 'Saving...' : 'Save'}
              </button>
            </>
          )}
        </div>
      </div>

      {/* Analysis dropdown (overlays below breadcrumb bar) */}
      {analysisExpanded && analysisResult && (
        <AnalysisDropdown
          result={analysisResult}
          onClose={() => setAnalysisExpanded(false)}
        />
      )}

      {/* Main area: tree + editor */}
      <div className="flex-1 flex overflow-hidden" style={{ position: 'relative' }}>
        {/* Left: File Tree */}
        <div
          className="shrink-0 overflow-y-auto"
          style={{
            width: 220,
            borderRight: '1px solid #e5e5e5',
            background: '#fafafa',
            padding: '8px 0',
          }}
        >
          {/* Project header */}
          <div style={{ padding: '6px 12px 10px', borderBottom: '1px solid #e5e5e5', marginBottom: 4 }}>
            <div className="flex items-center gap-2">
              <FolderOpen className="w-3.5 h-3.5" style={{ color: '#888' }} />
              <span style={{ fontSize: 12, fontWeight: 600, color: '#000' }} className="truncate">
                {project?.name}
              </span>
            </div>
            {project?.description && (
              <p style={{ fontSize: 10, color: '#888', marginTop: 2, paddingLeft: 18 }} className="truncate">
                {project.description}
              </p>
            )}
          </div>

          {/* Tree */}
          {skills.length === 0 ? (
            <p style={{ padding: '12px 16px', fontSize: 12, color: '#aaa' }}>No files yet</p>
          ) : (
            Object.entries(tree).map(([name, node]) => (
              <TreeNode
                key={name}
                name={name}
                node={node}
                selectedId={selectedSkill?.id}
                onSelect={selectSkill}
              />
            ))
          )}
        </div>

        {/* Center: Editor / Preview */}
        <div className="flex-1 flex flex-col min-w-0 overflow-hidden" style={{ position: 'relative' }}>
          {!selectedSkill ? (
            <div className="flex-1 flex items-center justify-center">
              <div style={{ textAlign: 'center', color: '#aaa' }}>
                <FileText className="w-10 h-10 mx-auto" style={{ opacity: 0.3, marginBottom: 8 }} />
                <p style={{ fontSize: 14 }}>Select a file to edit</p>
              </div>
            </div>
          ) : viewMode === 'preview' ? (
            <div className="flex-1 overflow-y-auto" style={{ padding: 24 }}>
              <MarkdownPreview content={content} />
            </div>
          ) : (
            <textarea
              value={content}
              onChange={(e) => handleContentChange(e.target.value)}
              className="skill-editor w-full h-full flex-1"
              spellCheck={false}
              style={{ resize: 'none' }}
            />
          )}

          {/* Floating toolbar (right side) */}
          <FloatingToolbar skill={selectedSkill} />
        </div>
      </div>
    </div>
  )
}
